import Head from 'next/head';
import { useTheme } from '../context/themeContext';
import styles from '../styles/Home.module.scss';

import { UserCard } from '../components/UserCard/UserCard';

export default function Home() {

  const {theme, switchTheme} = useTheme();

  return (
    <div>
      <Head>
        <title>Portifolio Isaque Alcantara</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='viewport' content='width=device-width, initial-scale=1.0'/>
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap" rel="stylesheet" />
      </Head>

      <main className={`${styles.container} ${theme}`}>
        <header>
          <button onClick={e => switchTheme()} > t </button>
        </header>
        <UserCard/>
      </main>

      <footer id='contact'>
      </footer>
    </div>
  )
}
