import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import { Header } from '../components/header/header'
import { useState } from 'react'

export default function Home() {

  const [theme, setTheme] = useState('light-theme');

  return (
    <div className={styles.container + ' ' + theme} id="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name='viewport' content='width=device-width, initial-scale=1.0'/>
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;700&display=swap" rel="stylesheet" />
      </Head>

      <Header theme={theme} setTheme={setTheme} />
      
    </div>
  )
}
